// constants/seeds.ts
import { Category, Product, Table } from '@/types';

// ---- CATEGORIES ----
export const seedCategories: Category[] = [
  { id: 'cat-entree', code: 'ENTREE', name: 'Entrées' },
  { id: 'cat-plat', code: 'PLAT', name: 'Plats' },
  { id: 'cat-dessert', code: 'DESSERT', name: 'Desserts' },
  { id: 'cat-accomp', code: 'ACCOMP', name: 'Accompagnements' },
  { id: 'cat-suppl', code: 'SUPPL', name: 'Suppléments' },
  { id: 'cat-boiss', code: 'BOISS', name: 'Boissons' },
];

export const defaultRestaurantId = 'seed-resto-1';

// ---- PRODUCTS ----
export const seedProducts: Product[] = [
  // Entrées
  {
    id: 'p-ent-1',
    name: 'Mini-samoussas',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 800,
    unit: 'pièce',
    description: 'Samoussas croustillants au bœuf',
    isAvailable: true,
  },
  {
    id: 'p-ent-2',
    name: 'Salade fraîche',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 700,
    unit: 'assiette',
    description: 'Salade de saison avec vinaigrette maison',
    isAvailable: true,
  },
  {
    id: 'p-ent-3',
    name: 'Soupe de légumes',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 900,
    unit: 'bol',
    description: 'Soupe légère aux légumes frais',
    isAvailable: true,
  },
  {
    id: 'p-ent-4',
    name: 'Bruschetta tomate',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 600,
    unit: 'pièce',
    description: 'Pain grillé, tomate, basilic et huile d’olive',
    isAvailable: true,
  },
  {
    id: 'p-ent-5',
    name: 'Nem au poulet',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 750,
    unit: 'pièce',
    description: 'Nem frit au poulet mariné',
    isAvailable: true,
  },
  {
    id: 'p-ent-6',
    name: 'Oeuf mimosa',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 500,
    unit: 'pièce',
    description: 'Œuf farci à la mayonnaise',
    isAvailable: true,
  },
  {
    id: 'p-ent-7',
    name: 'Assiette de charcuterie',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 1500,
    unit: 'assiette',
    description: 'Jambon, saucisson, pâté maison',
    isAvailable: true,
  },
  {
    id: 'p-ent-8',
    name: 'Avocat crevettes',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 1200,
    unit: 'assiette',
    description: 'Avocat frais garni de crevettes',
    isAvailable: true,
  },
  {
    id: 'p-ent-9',
    name: 'Carpaccio de bœuf',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 1600,
    unit: 'assiette',
    description: 'Tranches fines de bœuf cru, parmesan',
    isAvailable: true,
  },
  {
    id: 'p-ent-10',
    name: 'Raviolis vapeur',
    categoryId: 'cat-entree',
    restaurantId: defaultRestaurantId,
    price: 1000,
    unit: 'pièce',
    description: 'Raviolis asiatiques vapeur aux légumes',
    isAvailable: true,
  },

  // Plats
  {
    id: 'p-plt-1',
    name: 'Poulet DG',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 3500,
    unit: 'assiette',
    description: 'Poulet braisé avec plantains et légumes',
    isAvailable: true,
  },
  {
    id: 'p-plt-2',
    name: 'Poisson braisé',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 4000,
    unit: 'pièce',
    description: 'Poisson entier braisé, sauce tomate',
    isAvailable: true,
  },
  {
    id: 'p-plt-3',
    name: 'Boeuf sauce arachide',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 3800,
    unit: 'assiette',
    description: 'Bœuf mijoté dans une sauce arachide',
    isAvailable: true,
  },
  {
    id: 'p-plt-4',
    name: 'Côtelettes d’agneau',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 4200,
    unit: 'pièce',
    description: 'Agneau grillé aux herbes de Provence',
    isAvailable: true,
  },
  {
    id: 'p-plt-5',
    name: 'Lasagnes maison',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 3600,
    unit: 'part',
    description: 'Lasagnes à la bolognaise et béchamel',
    isAvailable: true,
  },
  {
    id: 'p-plt-6',
    name: 'Canard laqué',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 5000,
    unit: 'portion',
    description: 'Spécialité chinoise au canard caramélisé',
    isAvailable: true,
  },
  {
    id: 'p-plt-7',
    name: 'Spaghetti bolognaise',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 3000,
    unit: 'assiette',
    description: 'Pâtes à la bolognaise maison',
    isAvailable: true,
  },
  {
    id: 'p-plt-8',
    name: 'Pizza Margherita',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 2800,
    unit: 'pizza',
    description: 'Pizza italienne classique',
    isAvailable: true,
  },
  {
    id: 'p-plt-9',
    name: 'Brochettes de bœuf',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 3500,
    unit: 'portion',
    description: 'Brochettes grillées, accompagnement au choix',
    isAvailable: true,
  },
  {
    id: 'p-plt-10',
    name: 'Riz sauté aux crevettes',
    categoryId: 'cat-plat',
    restaurantId: defaultRestaurantId,
    price: 3200,
    unit: 'assiette',
    description: 'Riz parfumé sauté aux crevettes',
    isAvailable: true,
  },

  // Desserts
  {
    id: 'p-des-1',
    name: 'Beignets banane',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 600,
    unit: 'pièce',
    description: 'Beignets sucrés à la banane',
    isAvailable: true,
  },
  {
    id: 'p-des-2',
    name: 'Ananas frais',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 500,
    unit: 'portion',
    description: 'Ananas coupé et frais',
    isAvailable: true,
  },
  {
    id: 'p-des-3',
    name: 'Mousse au chocolat',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 900,
    unit: 'verrine',
    description: 'Mousse chocolat maison',
    isAvailable: true,
  },
  {
    id: 'p-des-4',
    name: 'Tarte aux pommes',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 1000,
    unit: 'part',
    description: 'Tarte croustillante aux pommes',
    isAvailable: true,
  },
  {
    id: 'p-des-5',
    name: 'Glace 2 boules',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 800,
    unit: 'coupe',
    description: 'Deux boules de glace au choix',
    isAvailable: true,
  },
  {
    id: 'p-des-6',
    name: 'Crème brûlée',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 1200,
    unit: 'ramequin',
    description: 'Crème vanille caramélisée',
    isAvailable: true,
  },
  {
    id: 'p-des-7',
    name: 'Salade de fruits',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 900,
    unit: 'bol',
    description: 'Fruits frais de saison',
    isAvailable: true,
  },
  {
    id: 'p-des-8',
    name: 'Cheesecake',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 1300,
    unit: 'part',
    description: 'Cheesecake aux fruits rouges',
    isAvailable: true,
  },
  {
    id: 'p-des-9',
    name: 'Brownie',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 1100,
    unit: 'part',
    description: 'Brownie chocolat fondant',
    isAvailable: true,
  },
  {
    id: 'p-des-10',
    name: 'Tiramisu',
    categoryId: 'cat-dessert',
    restaurantId: defaultRestaurantId,
    price: 1400,
    unit: 'verrine',
    description: 'Tiramisu italien au café',
    isAvailable: true,
  },

  // Boissons
  {
    id: 'p-boi-1',
    name: 'Coca-Cola',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 500,
    unit: '33cl',
    description: 'Boisson gazeuse sucrée',
    isAvailable: true,
  },
  {
    id: 'p-boi-2',
    name: 'Sprite',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 500,
    unit: '33cl',
    description: 'Boisson gazeuse citron-lime',
    isAvailable: true,
  },
  {
    id: 'p-boi-3',
    name: 'Fanta orange',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 500,
    unit: '33cl',
    description: 'Boisson gazeuse orange',
    isAvailable: true,
  },
  {
    id: 'p-boi-4',
    name: 'Eau minérale',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 300,
    unit: '50cl',
    description: 'Eau minérale plate',
    isAvailable: true,
  },
  {
    id: 'p-boi-5',
    name: 'Eau gazeuse',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 400,
    unit: '50cl',
    description: 'Eau minérale gazeuse',
    isAvailable: true,
  },
  {
    id: 'p-boi-6',
    name: 'Bière locale',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 1000,
    unit: 'bouteille',
    description: 'Bière blonde rafraîchissante',
    isAvailable: true,
  },
  {
    id: 'p-boi-7',
    name: 'Vin rouge',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 2500,
    unit: 'verre',
    description: 'Vin rouge maison',
    isAvailable: true,
  },
  {
    id: 'p-boi-8',
    name: 'Vin blanc',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 2500,
    unit: 'verre',
    description: 'Vin blanc sec',
    isAvailable: true,
  },
  {
    id: 'p-boi-9',
    name: 'Jus d’orange frais',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 1500,
    unit: 'verre',
    description: 'Pur jus pressé',
    isAvailable: true,
  },
  {
    id: 'p-boi-10',
    name: 'Smoothie mangue',
    categoryId: 'cat-boiss',
    restaurantId: defaultRestaurantId,
    price: 1800,
    unit: 'verre',
    description: 'Smoothie fruité mangue',
    isAvailable: true,
  },

  // Accompagnements
  {
    id: 'p-acc-1',
    name: 'Plantains frits',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 700,
    unit: 'portion',
    description: 'Bananes plantains frites',
    isAvailable: true,
  },
  {
    id: 'p-acc-2',
    name: 'Pommes sautées',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 800,
    unit: 'portion',
    description: 'Pommes de terre sautées',
    isAvailable: true,
  },
  {
    id: 'p-acc-3',
    name: 'Riz blanc',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 600,
    unit: 'portion',
    description: 'Riz blanc parfumé',
    isAvailable: true,
  },
  {
    id: 'p-acc-4',
    name: 'Légumes sautés',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 1000,
    unit: 'portion',
    description: 'Légumes frais sautés',
    isAvailable: true,
  },
  {
    id: 'p-acc-5',
    name: 'Purée de pommes de terre',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 900,
    unit: 'portion',
    description: 'Purée maison crémeuse',
    isAvailable: true,
  },
  {
    id: 'p-acc-6',
    name: 'Salade verte',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 700,
    unit: 'portion',
    description: 'Salade simple avec vinaigrette',
    isAvailable: true,
  },
  {
    id: 'p-acc-7',
    name: 'Frites',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 800,
    unit: 'portion',
    description: 'Pommes frites croustillantes',
    isAvailable: true,
  },
  {
    id: 'p-acc-8',
    name: 'Couscous',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 900,
    unit: 'portion',
    description: 'Semoule légère vapeur',
    isAvailable: true,
  },
  {
    id: 'p-acc-9',
    name: 'Haricots verts',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 900,
    unit: 'portion',
    description: 'Haricots verts sautés',
    isAvailable: true,
  },
  {
    id: 'p-acc-10',
    name: 'Riz cantonais',
    categoryId: 'cat-accomp',
    restaurantId: defaultRestaurantId,
    price: 1200,
    unit: 'portion',
    description: 'Riz sauté avec petits pois et jambon',
    isAvailable: true,
  },

  // Suppléments
  {
    id: 'p-sup-1',
    name: 'Sauce piquante',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 200,
    unit: 'portion',
    description: 'Sauce épicée maison',
    isAvailable: true,
  },
  {
    id: 'p-sup-2',
    name: 'Portion riz',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 500,
    unit: 'portion',
    description: 'Riz blanc en supplément',
    isAvailable: true,
  },
  {
    id: 'p-sup-3',
    name: 'Fromage râpé',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 400,
    unit: 'portion',
    description: 'Fromage râpé en supplément',
    isAvailable: true,
  },
  {
    id: 'p-sup-4',
    name: 'Pain',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 300,
    unit: 'portion',
    description: 'Petit pain individuel',
    isAvailable: true,
  },
  {
    id: 'p-sup-5',
    name: 'Mayonnaise',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 200,
    unit: 'portion',
    description: 'Sauce mayo maison',
    isAvailable: true,
  },
  {
    id: 'p-sup-6',
    name: 'Ketchup',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 200,
    unit: 'portion',
    description: 'Sauce ketchup',
    isAvailable: true,
  },
  {
    id: 'p-sup-7',
    name: 'Œuf au plat',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 500,
    unit: 'pièce',
    description: 'Œuf sur le plat',
    isAvailable: true,
  },
  {
    id: 'p-sup-8',
    name: 'Sauce champignon',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 600,
    unit: 'portion',
    description: 'Sauce crémeuse aux champignons',
    isAvailable: true,
  },
  {
    id: 'p-sup-9',
    name: 'Bacon grillé',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 800,
    unit: 'portion',
    description: 'Tranches de bacon grillées',
    isAvailable: true,
  },
  {
    id: 'p-sup-10',
    name: 'Chili extra',
    categoryId: 'cat-suppl',
    restaurantId: defaultRestaurantId,
    price: 300,
    unit: 'portion',
    description: 'Piment frais',
    isAvailable: true,
  },
];

// ---- TABLES ----
export const seedTables: Table[] = [];
