name: Expo CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  EXPO_NO_TELEMETRY: 1

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (CI)
        run: |
          echo "Installing with npm ci (lockfile enforced)";
          npm ci --no-audit --no-fund || (
            echo "npm ci failed; falling back to npm install";
            npm install --no-audit --no-fund
          )

      - name: Prettier check
        run: npx prettier --check .

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Lint check
        run: npm run lint

      - name: Expo doctor
        run: npx expo doctor

      - name: Check Expo export (Android)
        run: npx expo export --platform android --output-dir dist-android

      - name: Check Expo export (iOS)
        run: npx expo export --platform ios --output-dir dist-ios

      - name: Dry-run prebuild (native config)
        run: npx expo prebuild --no-install --clean
